version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: egressos
      POSTGRES_USER: egresso_user
      POSTGRES_PASSWORD: egresso_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://egresso_user:egresso_pass@db:5432/egressos
      JWT_SECRET: change-me
      COORDINATOR_USER: coordenador@ifce.edu.br
      COORDINATOR_PASSWORD: senha-segura
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:


